---
- name: jenkins setup for centos/rhel
  hosts:  127.0.0.1
  tasks:
    - name: setup repos 
      yum:  
        name: wget
        state:  present
  
    - name: downloading repos
      shell:  wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins.io/redhat-stable/jenkins.repo
   
    - name: 
      shell:  rpm --import http://pkg.jenkins.io/redhat-stable/jenkins.io.key
    
    - name: installing jenkins 
      yum:
        name: '{{ item }}' 
        state:  present 
      with_items:
        - jenkins
        - java-1.8.0-openjdk
      
    - name:
      firewalld:
        service:  '{{ item }}'
        permanent:  yes
        state:  enabled
      with_items:
        - http
        - jenkins
    
    - name:   enabling ports
      firewalld:
        port: 8080/tcp
        permanent:  yes
        state: enabled
    - name: starting jenkins
      service:
        name: jenkins
        state: started 
        enable: yes   
